whathaveidonenowblog_homepage:
    pattern:  /
    defaults: { _controller: whathaveidonenowblogBundle:Default:index }

whathaveidonenowblog_postscrewup:
    pattern:   /postscrewup
    defaults: { _controller: whathaveidonenowblogBundle:Default:postForm }

whathaveidonenowblog_testconfirm:
    pattern: /testconfirm
    defaults: {_controller: whathaveidonenowblogBundle:Default:success}



