whathaveidonenowblog_homepage:
    pattern:  /home
    defaults: { _controller: whathaveidonenowblogBundle:Default:index }

whathaveidonenowblog_post:
    pattern:   /post
    defaults: { _controller: whathaveidonenowblogBundle:Default:post }

whathaveidonenowblog_postscrewup:
    pattern:   /postscrewup
    defaults: { _controller: whathaveidonenowblogBundle:Default:postForm }


