whathaveidonenowblog_homepage:
    pattern:  /
    defaults: { _controller: whathaveidonenowblogBundle:Default:index }

whathaveidonenowblog_postscrewup:
    pattern:   /addpost
    defaults: { _controller: whathaveidonenowblogBundle:Default:postForm }

whathaveidonenowblog_viewpost:
    pattern: /post/{id}
    defaults: {_controller: whathaveidonenowblogBundle:Default:viewPost}



